openapi: 3.2.0
info:
  title: EVEDEX - Market Data Daily Statistics API
  version: 1.0.0
servers:
- url: https://market-data-api.evedex.com
tags:
- name: DailyStatistics
paths:
  /api/daily-statistics:
    get:
      tags:
      - DailyStatistics
      security:
      - AccessToken: []
      parameters:
      - in: query
        name: instrument
        schema:
          type: string
      responses:
        '200':
          description: 200 OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DailyStatisticsResponse'
      summary: Get api daily statistics
      x-summary-source: derived
      operationId: getApiDailyStatistics
      x-operation-id-source: derived
components:
  schemas:
    DailyStatisticsResponse:
      type: array
      items:
        type: object
        properties:
          instrument:
            type: string
          high:
            type: number
          low:
            type: number
          price:
            type: number
          volume:
            type: number
          volumeBase:
            type: number
          timecode:
            type: number
        required:
        - instrument
        - high
        - low
        - price
        - volume
        - volumeBase
        - timecode
  securitySchemes:
    InternalToken:
      type: http
      scheme: bearer
    AccessToken:
      type: http
      scheme: bearer
    RefreshToken:
      type: http
      scheme: bearer
