openapi: 3.2.0
info:
  title: EVEDEX - Exchange/billing-backend Payment Service API
  version: 1.0.0
servers:
- url: https://billing-api.evedex.com
tags:
- name: Payment Service
paths:
  /api/payment-service:
    get:
      tags:
      - Payment Service
      security: []
      responses:
        '200':
          description: 200 Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      summary: Get api payment service
      x-summary-source: derived
      operationId: getApiPaymentService
      x-operation-id-source: derived
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Error message
      required:
      - message
      description: Error response
  securitySchemes:
    InternalKey:
      type: http
      scheme: bearer
